# Generated by Django 4.0.10 on 2024-02-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakfast',
            options={'ordering': ('date',), 'verbose_name': 'Коуч-завтрак', 'verbose_name_plural': 'Расписание коуч-завтраков'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('date',), 'verbose_name': 'Игра', 'verbose_name_plural': 'Расписание игр'},
        ),
    ]
