# Generated by Django 4.0.10 on 2024-02-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_breakfast_options_alter_game_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferenceuser',
            old_name='conference',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='courseuser',
            old_name='course',
            new_name='event',
        ),
    ]
