# Generated by Django 4.0.10 on 2024-02-07 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текст рассылки')),
                ('type', models.CharField(choices=[('MASS', 'Массовая')], default='MASS', max_length=255, verbose_name='Тип рассылки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлена')),
                ('is_send', models.BooleanField(default=False, verbose_name='Отправить?')),
            ],
            options={
                'verbose_name': 'Массовая рассылка',
                'verbose_name_plural': 'Массовые рассылки',
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_payment', models.TextField(default='Оплата прошла успешно! Мы свяжемся с Вами накануне события.', verbose_name='Сообщение об успешной оплате')),
                ('fail_payment', models.TextField(default='К сожалению, оплата не прошла.', verbose_name='Сообщение о неуспешной оплате')),
            ],
            options={
                'verbose_name': 'Сообщение об оплате',
                'verbose_name_plural': 'Сообщения об оплате',
            },
        ),
        migrations.CreateModel(
            name='MassNotificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notifications', verbose_name='Изображение')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notifications.massnotification', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='GameNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текст рассылки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлена')),
                ('type', models.CharField(choices=[('BEFORE_EVENT', 'До события'), ('AFTER_EVENT', 'После события')], default='BEFORE_EVENT', max_length=255, verbose_name='Тип рассылки')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Рассылка по игре',
                'verbose_name_plural': 'Рассылки по игре',
            },
        ),
        migrations.CreateModel(
            name='ConferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текст рассылки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлена')),
                ('type', models.CharField(choices=[('BEFORE_EVENT', 'До события'), ('AFTER_EVENT', 'После события')], default='BEFORE_EVENT', max_length=255, verbose_name='Тип рассылки')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Рассылка по конференции',
                'verbose_name_plural': 'Рассылки по конференции',
            },
        ),
        migrations.CreateModel(
            name='BreakfastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текст рассылки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлена')),
                ('type', models.CharField(choices=[('BEFORE_EVENT', 'До события'), ('AFTER_EVENT', 'После события')], default='BEFORE_EVENT', max_length=255, verbose_name='Тип рассылки')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.breakfast', verbose_name='Завтрак')),
            ],
            options={
                'verbose_name': 'Рассылка по коуч-завтраку',
                'verbose_name_plural': 'Рассылки по коуч-завтраку',
            },
        ),
    ]
