# Generated by Django 4.0.10 on 2024-02-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Стоимость коуч-завтрака',
                'verbose_name_plural': 'Стоимость коуч-завтраков',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Завтрак',
                'verbose_name_plural': 'Завтраки',
            },
        ),
        migrations.CreateModel(
            name='PreRecordingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст вопроса предзаписи')),
            ],
            options={
                'verbose_name': 'Вопрос предзаписи',
                'verbose_name_plural': 'Вопросы предзаписи',
            },
        ),
        migrations.CreateModel(
            name='PromotionalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Промокод')),
                ('discount', models.PositiveIntegerField(verbose_name='Процент скидки')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('PLATINUM', 'PLATINUM'), ('NONE', 'NONE')], default='SILVER', max_length=255, verbose_name='Тип билета')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('limit', models.PositiveIntegerField(default=0, verbose_name='Лимит количества билетов')),
            ],
            options={
                'verbose_name': 'Категория билета',
                'verbose_name_plural': 'Категории билетов',
            },
        ),
        migrations.CreateModel(
            name='UserLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_limit', models.PositiveIntegerField(default=20, verbose_name='Лимит участников на коуч-завтрак')),
                ('game_limit', models.PositiveIntegerField(default=4, verbose_name='Лимит участников на игру')),
            ],
            options={
                'verbose_name': 'Лимит участников',
                'verbose_name_plural': 'Лимит участников',
            },
        ),
    ]
