# Generated by Django 4.0.10 on 2024-02-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('tg_user_id', models.CharField(max_length=255, verbose_name='user_id')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=255, null=True, verbose_name='Номер телефона')),
                ('tg_chat_id', models.CharField(max_length=255, verbose_name='chat_id')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='MenuButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Кнопка')),
                ('callback', models.CharField(choices=[('conference', 'Конференция'), ('course', 'Курс про деньги'), ('breakfast', 'Коуч-завтрак'), ('game', 'Игра'), ('personal_work', 'Хочу в личную работу'), ('podcast', 'Подкасты'), ('gift', 'Забрать подарок')], default=None, max_length=255, verbose_name='Обработчик')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Показать в боте')),
            ],
            options={
                'verbose_name': 'Кнопка меню',
                'verbose_name_plural': 'Кнопки меню',
                'ordering': ('pk',),
            },
        ),
    ]
