# Generated by Django 4.0.10 on 2024-02-14 11:41

from django.db import migrations, models


class CallbackTypes(models.TextChoices):
    """Перечисление типов колбеков для модели MenuButton."""

    CONFERENCE = 'conference', 'Конференция'
    COURSE = 'course', 'Курс про деньги'
    BREAKFAST = 'breakfast', 'Коуч-завтрак'
    GAME = 'game', 'Игра'
    PERSONAL_WORK = 'personal_work', 'Хочу в личную работу'
    PODCAST = 'podcast', 'Подкасты'
    GIFT = 'gift', 'Забрать подарок'


BUTTON_MAP = {
    CallbackTypes.CONFERENCE: 'КОНФА ПРО ДЕНЬГИ',
    CallbackTypes.COURSE: 'Я И ЕСТЬ СВОЙ ПРОЕКТ | ЭКОЛОГИЧНЫЕ ДЕНЬГИ',
    CallbackTypes.BREAKFAST: 'КОУЧ-ЗАВТРАКИ',
    CallbackTypes.GAME: 'ИГРА АТЛАНТОВ',
    CallbackTypes.PERSONAL_WORK: 'Хочу в личную работу',
    CallbackTypes.PODCAST: 'Подкаст ДУМАЙ | ДЕЛАЙ | БОГАТЕЙ',
    CallbackTypes.GIFT: 'Забрать подарок🎁',
}


def load_button_data(apps, schema_editor):
    """Загрузка модели MenuButton данными."""
    MenuButton = apps.get_model('telegram', 'MenuButton')

    for callback, name in BUTTON_MAP.items():
        button = MenuButton(
            title=name,
            callback=callback,
        )
        button.save()


def reverse_load_button_data(apps, schema_editor):
    """Откат загрузки модели MenuButton."""
    MenuButton = apps.get_model('telegram', 'MenuButton')
    MenuButton.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_button_data, reverse_load_button_data),
    ]


