# Generated by Django 4.0.10 on 2024-02-07 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonBreakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Коуч-завтрак',
            },
        ),
        migrations.CreateModel(
            name='CommonConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Конференция',
            },
        ),
        migrations.CreateModel(
            name='CommonCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс про деньги',
            },
        ),
        migrations.CreateModel(
            name='CommonGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Игра',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Забрать подарок',
            },
        ),
        migrations.CreateModel(
            name='PersonalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание')),
                ('telegram_link', models.URLField(verbose_name='Ссылка на Telegram ассистента')),
                ('whatsapp_link', models.URLField(verbose_name='Ссылка на Whatsapp ассистента')),
            ],
            options={
                'verbose_name': 'Хочу в личную работу',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Подкасты',
            },
        ),
        migrations.CreateModel(
            name='PodcastLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Показать в боте')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='configurations.podcast')),
            ],
            options={
                'verbose_name': 'Ссылка на подкаст',
                'verbose_name_plural': 'Ссылки на подкасты',
            },
        ),
        migrations.CreateModel(
            name='PersonalWorkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='configurations.personalwork', verbose_name='Хочу в личную работу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_work', to='telegram.botuser', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Запрос пользователя',
                'verbose_name_plural': 'Запросы пользователей',
            },
        ),
        migrations.AddField(
            model_name='personalwork',
            name='personal_users',
            field=models.ManyToManyField(related_name='users', through='configurations.PersonalWorkUser', to='telegram.botuser', verbose_name='Запросы от пользователей'),
        ),
        migrations.CreateModel(
            name='GiftLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Показать в боте')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='configurations.gift')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='GiftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='gifts', verbose_name='Изображение')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Показать в боте')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='configurations.gift')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='GiftFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('file', models.FileField(upload_to='gifts', verbose_name='Файл')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Показать в боте')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='configurations.gift')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games', verbose_name='Изображение')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='configurations.commongame')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='course', verbose_name='Изображение')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='configurations.commoncourse')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='ConferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='conference', verbose_name='Изображение')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='configurations.commonconference')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='BreakfastImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='breakfast', verbose_name='Изображение')),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='configurations.commonbreakfast')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
